main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index_view, name='home'),
]

personal_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('posts.urls', namespace='posts')),
    path('portifolio/', include('portifolio.urls', namespace='portifolio')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

portifolio/urls.py
from django.urls import path

from . import views

app_name = 'portifolio'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project-list'),
    path('project-create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('<slug:slug>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('<slug:slug>/update/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('<slug:slug>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),
]

posts/urls.py
from django.urls import path

from posts import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post-list'),
    path('post-create/', views.PostCreateView.as_view(), name='post-create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('<slug:slug>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('tag/<slug:slug>/', views.TagDetailView.as_view(), name='tag-detail'),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from mdeditor.fields import MDTextField


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Tag(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


STATUS_CHOICES = (
    (0, 'Draft'),
    (1, 'Publish'),
)


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    content = MDTextField()
    thumbnail = models.ImageField(upload_to='thumbnails/', blank=True, null=True)
    tags = models.ManyToManyField(Tag)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    featured = models.BooleanField(default=False)
    prev_post = models.ForeignKey('self', verbose_name='Previous Post', 
        related_name='previous_post', on_delete=models.SET_NULL, null=True, blank=True)
    nxt_post = models.ForeignKey('self', verbose_name='Next Post', 
        related_name='next_post', on_delete=models.SET_NULL, null=True, blank=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)

    class Meta:
        ordering = ['-created_on', 'title', ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'slug': self.slug})
  
    def get_update_url(self):
        return reverse('posts:post-update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('posts:post-delete', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on', ]

    def __str__(self):
        return f'Comment {self.body} by {self.name}'

posts/forms.py
from django import forms

from .models import Post, Comment


class PostCreateForm(forms.ModelForm):
    
    class Meta:
        model = Post
<<<<<<< HEAD
        fields = '__all__'


class CommentForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Your Name"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': "Your Email"}))
    body = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'Your Comment', 'rows': 4}))

    class Meta:
        model = Comment
        fields = ['name', 'email', 'body', ]
=======
        fields = '__all__'
>>>>>>> 976608b211e8bfb508bc4200d409bea05876e3ee

posts/views.py
from django.shortcuts import render, get_list_or_404, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
<<<<<<< HEAD
from django.http import HttpResponseRedirect
=======
>>>>>>> 976608b211e8bfb508bc4200d409bea05876e3ee

from posts.models import Post, Tag, Comment
from posts.forms import PostCreateForm, CommentForm


class PostListView(ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'posts/post_list.html'
    paginate_by = 9


class PostDetailView(DetailView):
    model = Post
    template_object_name = 'post'
    template_name = 'posts/post_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['comment_form'] = CommentForm()
        return context\

    def post(self, request, slug):
        post = self.get_object()
        if self.request.method == 'POST':
            form = CommentForm(self.request.POST)
            if form.is_valid():
                form.instance.post_id = post.id
                form.save()
            else:
                form = CommentForm()
        return HttpResponseRedirect(reverse('posts:post-detail', kwargs={'slug': post.slug}))


class PostCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    form_class = PostCreateForm
    template_name = 'posts/post_form.html'

    def test_func(self):
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return True
        return False


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'posts/post_update.html'
    success_message = 'Post updated successful.'

    def test_func(self):
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:post-list')
    success_message = 'Post deleted successful.'

    def test_func(self):
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return True
        return False


class TagDetailView(DetailView):
    model = Tag
    template_name = 'posts/post_tag_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = Tag.objects.get(slug=self.kwargs['slug'])
<<<<<<< HEAD
        context['object_list'] = tag.post_set.filter(status=1)
=======
        context['object_list'] = tag.post_set.all()
>>>>>>> 976608b211e8bfb508bc4200d409bea05876e3ee
        return context

posts/templates/posts/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137873696-1"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-137873696-1');
        </script>
        
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <title>Innocent Zenda</title>
    
        <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" type="image/png">

        <link rel="stylesheet" href="{% static '/css/styles.css' %}">
        <link rel="stylesheet" href="{% static '/css/codehilite_styles.css' %}">
        <link rel="stylesheet" href="{% static '/css/font-awesome.min.css' %}">
    
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    
        <link rel="stylesheet" href="{% static 'assets/css/LineIcons.css' %}">
    
        <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    
        <link rel="stylesheet" href="{% static 'assets/css/default.css' %}">
    
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static '/css/styles.css' %}">
        <link rel="stylesheet" href="{% static '/css/codehilite_styles.css' %}">
        <link rel="stylesheet" href="{% static '/css/font-awesome.min.css' %}">
    
    </head>

<body>
    <!-- Header -->
    <header id="home" class="header-area">
        <div class="navigation fixed-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <nav class="navbar navbar-expand-lg">
                            <a class="navbar-brand" href="/">
                                <img class='logo' src="{% static 'assets/images/logo.png' %}" alt="Logo">
                            </a> <!-- Logo -->
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                                <span class="toggler-icon"></span>
                                <span class="toggler-icon"></span>
                                <span class="toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item"><a class="page-scroll" href="/">Home</a></li>
                                    <li class="nav-item {% if request.path == '/portifolio/' %}active{% endif %}"><a class="page-scroll" href="{% url 'portifolio:project-list' %}">Portifolio</a></li>
                                    <li class="nav-item {% if request.path == '/blog/' %}active{% endif %}"><a class="page-scroll" href="{% url 'posts:post-list' %}">Blog</a></li>
                                </ul>
                            </div> <!-- navbar collapse -->
                        </nav> <!-- navbar -->
                    </div>
                </div> <!-- row -->
            </div> <!-- container -->
        </div> <!-- navigation -->
        </div> <!-- header content -->
    </header>
    <!-- Header ends -->

    
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} article alert-dismissible fade show mt-45 pt-125" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    
    {% block content %}
        
    {% endblock content %}

    <!-- Footer -->
    <footer id="footer" class="footer-area">
        <div class="footer-widget pt-130 pb-130">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="footer-content text-center">
                            <a href="/">
                                <img class='logo' src="{% static 'assets/images/logo.png' %}" alt="Logo">
                            </a>
                            <p class="mt-">
                                Love exploring and writing about technical stuff in a very simple language. Focus is to help other Developers, Managers and business owners to understand some of important technical issues.
                            </p>
                            <p>
                                Creating projects that reflects on solving the problem and accomplishing the goals.
                            </p>
                            <ul>
                                <li><a href="https://facebook.com/innocent.s.zenda" target="_blank"><i class="lni-facebook-filled"></i></a></li>
                                <li><a href="https://twitter.com/ZendaInnocent" target="_blank"><i class="lni-twitter-original"></i></a></li>
                                <li><a href="https://www.linkedin.com/in/zendainnocent" target="_blank"><i class="lni-linkedin-original"></i></a></li>
                                <li><a href="https://github.com/ZendaInnocent" target="_blank"><i class="lni-github-original"></i></a></li>
                                <li><a href="/#contact"><i class="lni-envelope"></i></a></li>
                            </ul>
                        </div> <!-- footer content -->
                    </div>
                </div> <!-- row -->
            </div> <!-- container -->
        </div> <!-- footer widget -->
        <div class="footer-copyright pb-20">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="copyright-text text-center pt-20 ">
                            <p class='text-secondary'>Copyright &copy; 2020.
                                <a class='text-light' href="/" rel="nofollow">Innocent
                                    Zenda
                                </a>
                            </p>
                        </div> <!-- copyright text -->
                    </div>
                </div> <!-- row -->
            </div> <!-- container -->
        </div> <!-- footer widget -->
    </footer>

    <!-- Footer ends -->

    <!-- Back to top button -->

    <a href="#" class="back-to-top"><i class="lni-chevron-up"></i></a>
    
    


    <!--====== jquery js ======-->
    <script src="{% static 'assets/js/vendor/modernizr-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>

    <!--====== Bootstrap js ======-->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>

    <!--====== Magnific Popup js ======-->
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>

    <!--====== Parallax js ======-->
    <script src="{% static 'assets/js/parallax.min.js' %}"></script>

    <!--====== Counter Up js ======-->
    <script src="{% static 'assets/js/waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>


    <!--====== Appear js ======-->
    <script src="{% static 'assets/js/jquery.appear.min.js' %}"></script>

    <!--====== Scrolling js ======-->
    <script src="{% static 'assets/js/scrolling-nav.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easing.min.js' %}"></script>


    <!--====== Main js ======-->
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!--====== slugify js ======-->
    <script src="{% static 'assets/js/slugify.js' %}"></script>
</body>
</html>

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/base.html' %}

{% block title %}
    Delete Post -
{% endblock title %}
    

{% block content %}
<div class="mt-5 pt-5">
    <div class="container my-5">
        <form method="POST">
            {% csrf_token %}
            <p>You want to delete {{ object }}?</p>
            <div class="mt-3">
                <a href="{{ object.get_absolute_url }}" class="btn btn-secondary mr-2">No</a>
                <button class="btn btn-danger">Yes, Delete</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}
    

posts/templates/posts/post_delete.html
{% extends 'posts/base.html' %}

{% block title %}
    Delete Post -
{% endblock title %}
    

{% block content %}
<div class="mt-5 pt-5">
    <div class="container my-5">
        <form method="POST">
            {% csrf_token %}
            <p>You want to delete {{ object }}?</p>
            <div class="mt-3">
                <a href="" class="btn btn-secondary mr-2">No</a>
                <button class="btn btn-danger">Yes, Delete</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}
    

posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %}
{% load static %}
{% load markdown_extras %}
{% load crispy_forms_tags %}

{% block title %}
    {{ post.title }} -
{% endblock title %}

{% block content %}
    
    <div class="container py-5">
        <div class="main pt-5 mt-5">
            <div class="article">
                <h2>{{ post.title }}</h1>
                <div class="row py-3">
                    <div class="tags col-6">
                        {% for tag in post.tags.all %}
                        <a class="mr-2 p-2" href="{% url 'posts:tag-detail' tag.slug %}">
                            {{ tag }}
                        </a>
                        {% endfor %}
                    </div>
                    <div class="col-6 text-right">
                        <a href="{% url 'posts:post-update' post.slug %}" class="mr-2 btn btn-success">Update</a>
                        <a href="{% url 'posts:post-delete' post.slug %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
                <div>
                    {{ post.content | markdown |safe }}
                </div>
            
                <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row mt-5 pt-4">
                    {% if post.prev_post %}
                    {% if post.previous_post.first.status == 1 %}
                    <a href="{{ post.prev_post.get_absolute_url }}" class="btn btn-outline btn-lg prev-post text-left d-flex align-items-center">
                        <div class="icon prev mr-3">
                          <i class="fa fa-2x fa-angle-left"></i>
                        </div>
                        <div class="text">
                          <strong class="text-primary">Previous Post </strong>
                          <h6>{{ post.prev_post.title }}</h6>
                        </div>
                      </a>
                    {% endif %}
                    {% endif %}
                    
                    {% if post.nxt_post %}
                    {% if post.next_post.first.status == 1 %}
                    <a href="{{ post.nxt_post.get_absolute_url }}" class="btn btn-outline btn-lg next-post text-right d-flex align-items-center justify-content-end">
                        <div class="text">
                          <strong class="text-primary">Next Post </strong>
                          <h6>{{ post.nxt_post.title }}</h6>
                        </div>
                        <div class="icon next ml-3">
                          <i class="fa fa-2x fa-angle-right">   </i>
                        </div>
                      </a>
                    {% endif %}
                    {% endif %}
                      
                </div>
                
                {% if post.comments %}      
                <div class="post-comments">
                  <header>
                    <h3 class="h6">Comments <span class="no-of-comments">({{ post.comments.count }})</span></h3>
                  </header>
                  {% for comment in post.comments.all %}
                  <div class="comment">
                      <div class="comment-header d-flex justify-content-between">
                        <div class="user d-flex align-items-center">
                            <div class="image">
                              <img src="{% static 'img/user.svg' %}" alt="..." class="img-fluid rounded-circle">
                            </div>
                          
                          <div class="title"><strong>{{ comment.name }}</strong><span class="date">{{ comment.created_on|date }}</span></div>
                        </div>
                      </div>
                      <div class="comment-body">
                        <p>
                          {{ comment.body }}
                        </p>
                      </div>
                    </div>
                  {% endfor %}
                </div>
                {% endif %}
               
                  
                <div class="div mt-4">
                  <form method='POST'>
                    {% csrf_token %}
                    {{ comment_form | crispy }}
                    <button class="main-btn">Comment</button>
                  </form>
                </div>
                
            </div>
            
        </div>
    </div>
    
{% endblock content %}

posts/templates/posts/post_form.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="mt-5 pt-5">
    <form method="POST" enctype="multipart/form-data" class="col-md-8 offset-md-2 my-5 pt-4">
        <h2 class="mb-4">Create Post</h2>
        {% csrf_token %}
        {{ form.media }}
        {{ form | crispy }}
        <button class="btn btn-primary">Create Post</button>
    </form>
</div>
{% endblock content %}

posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}
{% load static %}
{% load markdown_extras %}


{% block content %}

<section id="blog" class="blog-area pt-125 pb-130 mt-45">
    <div class="container">
        <div class="row justify-content-center">
            {% for post in object_list %}
            <div class="col-lg-4 col-md-8 col-sm-9">
                    <div class="card">
                        <a href="{{ post.get_absolute_url }}">
                            {% if post.thumbnail %}
                            <img class="card-img-top" src="{{ post.thumbnail.url }}" alt="Card image cap">
                            {% endif %}
                        </a>
                        <div class="card-body">
                            <a href="{{ post.get_absolute_url }}">
                                <h4 class="card-title">
                                    {{ post.title }}
                                </h4>
                            </a>
                            <p class="card-text">
                                {{ post.content | markdown | safe }}
                                <br>
                                {{ post.created_on | date }}
                            </p>
                        </div>
                    </div>
                </div>
            {% empty %}
            <h4>No posts yet.</h4>
            {% endfor %}
        </div> <!-- row -->
        <div class="row mt-5 justify-content-center footer-content">
            <!-- Pagination -->
            {% if is_paginated %}
              <ul>
                {% if page_obj.has_previous %}
                  <li>
                    <a href="?page=1" class="text-light" style="font-size: large;">
                     First
                    </a>
                  </li>
                  <li>
                    <a href="?page={{ page_obj.previous_page_number }}" class="text-light">
                     <i class="fa fa-angle-left"></i>
                    </a>
                  </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                  <li>
                    <a href="?page={{ num }}" class="text-light">{{ num }}</a>
                  </li>
                  {% elif num > page_obj.number|add:'-1' and num < page_obj.number|add:'1' %}
                      <li>
                        <a href="?page={{ num }}" class="text-light">{{ num }}</a>
                      </li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li>
                    <a href="?page={{ page_obj.next_page_number }}" class="text-light">
                      <i class="fa fa-angle-right"></i>
                    </a>
                  </li>
                  <li>
                    <a href="?page=last" class="text-light" style="font-size: large;">
                      Last
                    </a>
                  </li>
                {% endif %}
              </ul>
           
            {% endif %}
          </div>
        </div> <!-- row -->
    </div> <!-- container -->
</section>

{% endblock content %}

posts/templates/posts/post_tag_detail.html
{% extends 'posts/base.html' %}
{% load static %}
{% load markdown_extras %}


{% block content %}
<section id="blog" class="blog-area pt-125 pb-130">
    <div class="container">
        <div class="row justify-content-center">
            {% for post in object_list %}
                <div class="col-lg-4 col-md-6 mb-3">
                    <div class="card">
                        <a href="{{ post.get_absolute_url }}">
                            {% if post.thumbnail %}
                            <img class="card-img-top" src="{{ post.thumbnail.url }}" alt="Card image cap">
                            {% endif %}
                        </a>
                        <div class="card-body">
                            <a href="{{ post.get_absolute_url }}">
                                <h4 class="card-title">
                                    {{ post.title }}
                                </h4>
                            </a>
                            <p class="card-text">
                                {{ post.content | markdown | safe }}
                                <br>
                                {{ post.created_on | date }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div> <!-- row -->
        
    </div> <!-- container -->
</section>
{% endblock content %}

posts/templates/posts/post_update.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update Post -
{% endblock title %}

{% block content %}
<div class="mt-5 pt-5">
    <form action="" method="POST" class="col-md-8 offset-md-2 my-5">
        <h2 class="mb-4">Update Post</h2>
        {% csrf_token %}
        {{ form.media }}
        {{ form | crispy }}
        <button class="main-btn mt-4">Update Post</button>
    </form>
</div>
{% endblock content %}
    